### ISSUE TITLE
BUG: Failed to Format Log Message

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-utils#111]
## Issue
Our logs are populated with many `failed to format log message: "'some message'" not found`

This populates our logs with `ERROR` messages which makes it more difficult to track actual errors. It could be that the [order of imports](https://stackoverflow.com/a/20280587) needs to change. 

## Acceptance Criteria
The message no longer appears in our logs. Previously we had tested this in Dev and thought it was working. This requires more rigorous testing so it can be completed.

## Additional Information

![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/e7a12888-9ca6-42cc-a818-1e68d60ab78c)
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/a0cad0c0-a827-443c-b5a4-b4e92d706502)
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/028fc859-3731-4aac-93b9-4171a7dd24c9)
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/4f9f4b7e-0c7c-4d1f-9de2-adee09bca3f8)

**Comment by kalbfled** [comment]
This is causing a significant number of logging errors.  During the March 23rd deployment, we began with around 125k errors during the day and accumulated 1000s more in real time.
![image](https://user-images.githubusercontent.com/5375929/227396175-bfac1b7e-f3f2-43a6-aa58-ac227e61cdf2.png)

**Comment by cris-oddball** [comment]
@kalbfled can you please point this ticket?

**Comment by kalbfled** [comment]
I implemented a prospective solution that needs to be tested.  See PR 118.

**Comment by cris-oddball** [comment]
awaiting 1222, which is the test ticket.

**Comment by cris-oddball** [comment]
Closing this, because the testing will be on 1222
