### ISSUE TITLE
BUG: logging 'not found errors'

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-utils#115]
## Description
There are logs in the production that show an error for an expected property that is not found in a response from an API route. Given that the response itself actually shows the key that is claimed to be missing, there is something amiss here. The file is in notification_utils logging.py: `logger.exception("failed to format log message: {} not found".format(e))`

## Steps to Reproduce
Search production logs for "`failed to format log message"` and looks for ones like the following:
```
ERROR 2023-04-05 21:24:30,934 /usr/local/lib/python3.8/site-packages/notifications_utils/logging.py:204: failed to format log message: "'appSid'" not found
```

or 
```
ERROR 2023-04-05 21:26:29,046 /usr/local/lib/python3.8/site-packages/notifications_utils/logging.py:204: failed to format log message: "'success'" not found
```

The full log sequence for one such event is as follows:
```
76fdfebf-f5b1-44b7-af26-a36278ac8445 POST https://api.va.gov/v2/notifications/push 201 2.66969
INFO 2023-04-05 22:31:54,673 /app/app/va/vetext/client.py:49: VEText response: {'success': True, 'statusCode': 200}
VEText response: {'success': True, 'statusCode': 200}
KeyError: "'success'"
log_record['message'] = log_record['message'].format(**log_record)
File "/usr/local/lib/python3.8/site-packages/notifications_utils/logging.py", line 202, in process_log_record
Traceback (most recent call last):
ERROR 2023-04-05 22:31:54,673 /usr/local/lib/python3.8/site-packages/notifications_utils/logging.py:204: failed to format log message: "'success'" not found
```

## Impact/Urgency
Medium - Annoying. Fills the logs with what appear to be erroneous errors. Also, logging costs money! Hard to sift the wheat from the chaff.

## Expected Behavior

- [ ] There are no more such logs generated when a property clearly exists in a response.

## QA Considerations
QA to take a look at logging as the code gets merged up the food chain.

**Comment by cris-oddball** [comment]
@kalbfled can you please point this ticket?

**Comment by kalbfled** [comment]
I implemented a prospective solution that needs to be tested.  See PR 118.

**Comment by cris-oddball** [comment]
awaiting 1222, which is the test ticket.
