### ISSUE TITLE
Utils: PyPDF2 deprecation

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-utils#117]
## User Story - Business Need

`PyPDF2` is deprecated and should be replaced with `pypdf`.  See the note [here](https://pypi.org/project/PyPDF2/).  This change should be made in concert with a [similar change to notification-api](https://github.com/department-of-veterans-affairs/notification-api/issues/1221), which also depends on PyPDF2.

- [x] Discussed with QA

### User Story(ies)
**As a** stakeholder in VA Notify
**I want** to keep all dependencies up to date
**So that** the application remains secure

### Additional Info and Resources
- PyPDF [changelog regarding PyPDF2](https://pypdf.readthedocs.io/en/latest/meta/CHANGELOG.html#pypdf2-1-x)

## Engineering Checklist
_**Required**_

- [x] In [setup.py](https://github.com/department-of-veterans-affairs/notification-utils/blob/master/setup.py#L39), replace the `PyPDF2` requirement with `pypdf`.

## Acceptance Criteria

- [x] After importing the updated utils repo into notification-api, the containers build without error using pypdf
- [x] All unit tests pass

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/117?planning-poker) with Zenhub @cris-oddball @EvanParish @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov
