### ISSUE TITLE
Upgrade all Python requirements

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-utils#130]
## User Story - Business Need

In [setup.py](https://github.com/department-of-veterans-affairs/notification-utils/blob/master/setup.py), upgrade Python dependencies to specify the latest possible versions.

- [ ] Ticket is understood and QA has been contacted

### Additional Info and Resources

This ticket should not commence before these tickets are closed:

- #129
- #117
- [notification-api 1221](https://github.com/department-of-veterans-affairs/notification-api/issues/1221)

## Engineering Checklist

- [ ] For loosely specified dependencies, set the minimum version to the version currently specified in the api repo's requirements.txt
- [ ] Upgrade more tightly specified dependencies, make code changes as necessary.
- [ ] remove `python-json-logger` or add a comment as to why it's necessary
- [ ] Passes all tests locally

## Acceptance Criteria

Repo dependencies are updated without any broken functionality. Tickets created for any updates that could not not be updated.

## QA Considerations

- [ ] QA Regression tests pass after deploying this code.

**Comment by npmartin-oddball** [comment]
Closing/no longer relevant.
