### ISSUE TITLE
Spike: Understanding template formatting for mistunes upgrade

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-utils#134]
## User Stories

As a Notify Portal user,
I want to preview my templates with auto-formatting.
so that I can see how they will appear to veterans.

As a notification-utils developer,
I want to apply auto-formatting to markdown in templates
so that messages to veterans have a consistent format.

## Additional Information

For #129, we attempted to upgrade mistune but concluded that is not feasible.  Instead, we should recreate the functionality without using mistune.  Before we undertake this effort, we need a summary of all the existing formatting rules codified in [formatters.py](https://github.com/department-of-veterans-affairs/notification-utils/blob/master/notifications_utils/formatters.py) and [templates.py](https://github.com/department-of-veterans-affairs/notification-utils/blob/master/notifications_utils/template.py).

## Engineering Checklist

- [ ] Using a combination of code review, the [existing unit tests](https://github.com/department-of-veterans-affairs/notification-utils/blob/master/tests/test_formatters.py), and verification/experimentation in Portal, document all auto-formatting changes produced by the current implementation.
- [ ] Propose an alternative to mistune.  [Markdown](https://pypi.org/project/Markdown/) is one option.

## Acceptance Criteria

- [ ] The information in the Engineering Checklist has been documented and shared

**Comment by cris-oddball** [comment]
Needs a review from @k-macmillan to get it into a refinement.

**Comment by kalbfled** [comment]
This is a spelunk of about 1,300 lines in two files.

**Comment by npmartin-oddball** [comment]
Closing. Will open a spike ticket.
