### ISSUE TITLE
Remove PyPDF

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-utils#141]
PyPDF is no longer used by notification-api repository and can be removed

## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** developer   <br>
**I want** to remove unused libraries <br>
**So that** code is  easier to maintain and upgrade in the future 

### Additional Info and Resources
[Issue 1178](https://github.com/department-of-veterans-affairs/notification-api/issues/1178)
[Issues 1163 ](https://github.com/department-of-veterans-affairs/notification-api/issues/1163)

## Engineering Checklist

- [ ] Removed pypdf from setup.py
- [ ] Deleted pypdf_consts.py from test folder
- [ ] Deleted the templates under "letter_pdf" folder
- [ ] Deleted pdf.py
- [ ] Deleted test_pdf.py
- [ ] Deleted LetterPrintTemplate + LetterImageTemplate from template.py
- [ ] API is updated with new Utils master

## Acceptance Criteria
- [ ] All notification_utils tests pass
- [ ] All notifications-api tests pass 
- [ ] All notification-api-qa tests pass

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._
- [ ] QA suite passes in Perf
- [ ] Additional manual testing as determined by conversation with developer
- [ ] (Strike) Portal preview regression to ensure no email preview functionality is impacted

## Potential Dependencies
https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1482

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/141?planning-poker) with Zenhub @babyjunior56 @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov @cris-oddball

**Comment by mjones-oddball** [comment]
@babyjunior56 once you make the new api cleanup ticket (not dao/models) please add as a blocker dependency here. Or ask me and I can!

**Comment by npmartin-oddball** [comment]
Closing/no longer relevant.
