### ISSUE TITLE
Configure Debug Log Level

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-utils#146]
## User Story - Business Need
Currently logging at debug level doesn't show up in cloudwatch for any environment, so the lowest level of logs we can see in any environment is `info`. We would like to be able to see logs at `debug` level in lower environments, especially to help with testing, and not polluting prod logs.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify Engineer
**I want** update our logging
**So that** we can see debug logs in cloudwatch in our lower environments (dev, perf, staging)

### Additional Info and Resources

See [notifications_utils/logging.py](https://github.com/department-of-veterans-affairs/notification-utils/blob/master/notifications_utils/logging.py)

## Engineering Checklist

- [x] check into how logging is configured
- [x] logging level set to debug in lower environments (dev | perf | staging) through an env value (task definition)
- [x] remove any TODO comments related to this ticket in the API code

## Acceptance Criteria

- Cloudwatch / Datadog properly shows messages that are printed using `current_app.logger.debug('')`
- Huddle with team and explain how logging works

**Comment by cris-oddball** [comment]
@EvanParish can you please fill in this ticket a bit more with a user story?

**Comment by EvanParish** [comment]
@cris-oddball I updated the description. It's still a little light on details, but that's the point of the ticket. If I knew how to do it I would have done it already.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/146?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by MackHalliday** [comment]
Friday 
- Learned about logging into the `notification-api` repo and how the `notification-utils` package functions 
- Created `if/else` statement in `notification-utils` to handle different environments 

Today 
- Try to test with `notification-api` locally using Postman

**Comment by MackHalliday** [comment]
Today: 
- Debug locally
- Work on environmental issues with David 

Cannot get logs to filter if using the method `logger.init_app` from the `notification-utils`. I can only get the logs to filter correctly if done directly in the `notification-api` repo in the `def create_app` method. 

I set up testing locally on a branch in the `notification-api` repo.  Toggling the line `application.logger.setLevel('DEBUG')` to `application.logger.setLevel('INFO')` and then hit the end `GET /service` locally will filter out DEBUG logs. 
<img width="1686" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE9SQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5026f00f84fbeba4a1aa1c6512c6700146cee9bf/Screenshot%202024-06-25%20at%2011.18.49%E2%80%AFPM.png" alt="Screenshot 2024-06-25 at 11.18.49 PM.png" />


See PR https://github.com/department-of-veterans-affairs/notification-api/pull/1843/files

**Comment by MackHalliday** [comment]
https://oddball.slack.com/archives/C036AE08HA7/p1719412715539529

Working with @EvanParish after standup to review on DEV

**Comment by MackHalliday** [comment]
Yesterday 
- Complete AC
- Add unit testing and test local 

Today 
- Test in Dev 
- Submit PR

**Comment by MackHalliday** [comment]
I'll be explaining logging in our pain points meeting this Friday.

**Comment by MackHalliday** [comment]
Yesterday 
- Submit PR for review and testing in DEV

Today 
- Respond to PR feedback and close ticket
