### ISSUE TITLE
Add h3 Header to Email Formatting

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-utils#154]
## User Story - Business Need
We currently support `h1` and `h2` in our markdown. Clients have expressed interest in `h3`. Add `h3` header support and validate it is working correct.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Service
**I want** to specify up to h3 headers
**So that** I can section emails to the fullest

### Additional Info and Resources

Existing header logic:
<img width="836" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODB3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75075ae01dce250821fcff45400f4c746e273e4d/image.png" alt="image.png" />

Existing jinja template:
<img width="444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODR3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83d59f3493ff4cfb234b05f61794b68c1a38c5ab/image.png" alt="image.png" />

May be necessary here too, unsure:
<img width="558" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUF3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32e47b7c95a7b52bf819a6a6fc44e52919b3db2d/image.png" alt="image.png" />

dvla seemed to be associated with letter stuff, so the last one may be unnecessary. 

Header sizes:
<img width="335" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzR4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--339a0684036d23ca65509bc14674f3ec9384e865/image.png" alt="image.png" />

## Acceptance Criteria

- [x] h3 headers work in templates and display in emails
- [x] API PR points to new utils version after this is merged
- [x] Headers match the image in additional information that shows header sizes
- [x] New header formatting matches UX expectations (reach out to UX)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/154?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman @cris-oddball

**Comment by npmartin-oddball** [comment]
UX (Ian H. and Elissa) will provide final signoff on this ticket.

**Comment by kalbfled** [comment]
I merged the changes to the notification-utils repo after @ElissaFolk gave me the green light and after the usual PR reviews.  I still need API changes.
