### ISSUE TITLE
BUG: GA4 Migration: Broken image icon appears in Email when GA4 Dynamic URL Enabled

### ISSUE THREAD

**Issue by MackHalliday** [department-of-veterans-affairs/notification-utils#158]
## Description
When GA4 pixel tracking is enabled for email notifications, a broken image icon appears in all emails. 
This seems to happen no matter the browser or email platform. 

We likely need to update the `email_template.jinja2` file in the `notification-utils` repo. 

**NOTE: Any updates to the `notifications-utils` will require an dependency update in the `notification-api` application**

<img width="700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG5mQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c402d3709c7c03a41680ab718539ec22889d605a/Screenshot%202024-07-15%20at%203.37.57%E2%80%AFPM.png" alt="Screenshot 2024-07-15 at 3.37.57 PM.png" />

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. Send an notification email in DEV using any email template. 
2. View sent email in browser - Broken email icon will be visible.  

## Impact/Urgency

High

## Expected Behavior

- [ ] No broken image icon appears. 
- [ ] The embedded dynamic tracking URL image is not visible. 

## QA Considerations
- [ ] As above in expected behavior
- [ ] Look for any edge cases and raise them if found

## Additional Info & Resources

- Bug created in ticket [#153](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-utils/153) 
- GA pixel tracking urls are embedded when `GOOGLE_ANALYTICS_ENABLED` environment variable is `True` and then `GA4_open_email_tracking` is populated in the`HTMLEmailTemplate` class. The `HTMLEmailTemplate` is apart of the `notification-utils` repo. 
- We likely need to update the `email_template.jinja2` file in the `notification-utils` template. 
- **NOTE: Any updates to the `notifications-utils` will require an dependency update in the `notification-api`**
<img width="1511" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeURmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcb376ba9ae8dffdc143b99c743d53516f1f417e/Screenshot%202024-07-15%20at%203.42.26%E2%80%AFPM.png" alt="Screenshot 2024-07-15 at 3.42.26 PM.png" />

**Comment by mjones-oddball** [comment]
Canceling this ticket and moving the work to #1847 because we plan to host a png in our repo to return as part of this process. No work needed in Utils. @MackHalliday pls update the scope of that ticket!
