### ISSUE TITLE
Master Branch Rename: Utils

### ISSUE THREAD

**Issue by coreycarvalho** [department-of-veterans-affairs/notification-utils#162]
## User Story - Business Need

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** DevOps engineer    
**I want** to rename the `master` branch to `main` in this repository  
**So that** our branch naming aligns with industry standards and promotes inclusive terminology.

### Additional Info and Resources
- [GitHub guide on renaming the default branch](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch) <--- follow step there to rename on GitHub and have Evan or Kyle add the correct permissions to main for the group to be able to merge.
- Steps to rename the branch:
  1. Update local clones:
     ```sh
     git branch -m master main
     git fetch origin
     git branch -u origin/main main
     git remote set-head origin -a
     ```
  3. Update documentation to reflect the branch name change.

## Acceptance Criteria
- [x] The `master` branch has been successfully renamed to `main` in this repository.
- [x] All documentation and code references to the `master` branch have been updated to `main`.
- [x] Team is notified in Slack to run the `Update local clones` directions from above.
- [x] API is updated once this repository is updated by running `poetry update notification-utils` in an API branch and submitting a PR.

## QA Considerations
- Ensure that all automated tests run successfully after the branch rename.
- Verify that the deployment pipeline still functions correctly with the new branch name.
- Check that any links or references to the branch in the documentation are updated and correct.

## Potential Dependencies
- Coordination with other teams that might have dependencies on the `master` branch.
- The API is dependent on the naming of the default branch of this repository.

**Comment by cris-oddball** [comment]
_CI/CD pipeline has been updated to reference the main branch._

There is no CI/CD associated with this. We also want to ensure that the API gets updated when this branch is merged, so please add a bullet point about running _poetry update notification-utils_ in an API branch and then creating a PR out of it so that the API picks up this change.

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/162?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by cris-oddball** [comment]
PR approved and merged, sent up via pipeline.
