### ISSUE TITLE
Update Utils dependencies

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-utils#163]
## User Story - Business Need

We wish to keep dependencies up to date so that we do not need such massive overhauls of our system. This is a recurring task to update all dependencies we are able to update. Any conflicts shall get a dedicated ticket. This task should be a day of work at most because it only updates non-breaking changes.

- [x] Ticket is understood and QA has been contacted

### User Story

**As** VA Notify,
**I want** to keep our service up to date
**So that** we are secure and as free of bugs as possible.

### Additional Info and Resources

- All dependencies are in requirements files of various sorts.

## Engineering Checklist

- [x] Review "Tech Debt" tickets in backlog to identify packages already known to have breaking changes (**don't try to upgrade these**) For example, mistunes should not be upgraded on this ticket.
 - [x] Review the setup.py file as it contains dependencies
- [x] Review [open Dependabot PRs](https://github.com/department-of-veterans-affairs/notification-utils/pulls/app%2Fdependabot) to determine where the changes will take place (open them and look at the files touched). 
  -  **Do not modify these PRs**
- [x] Passes all tests locally
- [x] Passes QA Suite regression testing against Dev with the API pulling in this latest commit
- [ ] If there are any failures, create a ticket, and label it "tech debt"
  - [ ] Created ticket has the package name in the title
- [x] requires an API PR to pull in the latest commit from utils (ask if this is not understood)
- [x] Update the Slide deck with the key win and a demo slide

## Acceptance Criteria

Repo dependencies are updated and we have no broken functionality. Issues opened by Dependabot or listed in the Makefile are resolved. Tickets with the "tech debt" label created for any updates we could, or should, not do.

## QA Considerations

- [x] Affected Dependabot PRs are closed after merge (may need to rebase them using dependabot command)
- [x] QA Regression tests pass after deploying this and API code.

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/163?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by kalbfled** [comment]
I am only updating dependencies that are tightly specified (i.e. not `>=`).  These include pyyaml and test dependencies.

**Comment by kalbfled** [comment]
There were no failures.  I added a bullet point to the "Engineering wins" section, but there's nothing to demo in a separate slide.
