### ISSUE TITLE
ImportError with PyPDF2 >= 2.0.0

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-utils#84]
The PyPDF2 package, on which this repo depends, includes [breaking changes in v2.0.0](https://raw.githubusercontent.com/py-pdf/PyPDF2/main/CHANGELOG) that raise ImportError in this code.  For example, in pdf.py, the exception "PdfReadError" has been movied from the "utils" module to the "errors" module.

[Notification-api](https://github.com/department-of-veterans-affairs/notification-api) depends on notification-utils and is unable to update to the latest version of PyPDF2.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/84?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360
