### ISSUE TITLE
Update latest dependencies in utils repo

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-utils#90]
## Issue
There are multiple dependencies out of date. Update to the most current versions possible.

## Checklist
- [ ] Deployment of all repos to Dev
- [ ] All tests pass

## Additional Info
Starting point:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/8e687e23-7866-4cf7-ac34-40479de9ec51)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/90?planning-poker) with ZenHub @EvanParish @ianperera @jessecanderson @k-macmillan @kalbfled @maham360 @jakehova
